version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  server-config:
    container_name: server-config
    restart: always
    build:
      context: ./server-config
    ports:
      - "8888:8888"
    healthcheck:
      test: curl -sS http://127.0.0.1:8888 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3

  eureka-server:
      container_name: eureka-server
      restart: always
      build:
        context: ./eureka-server
      ports:
        - "8761:8761"
      restart: always
      depends_on:
        server-config:
          condition: service_healthy
      links:
        - server-config

  search-service:
      container_name: search-service
      build: ./search
      ports:
        - "8090:8090"
      depends_on:
        server-config:
          condition: service_healthy
      links:
        - server-config
        - eureka-server

  search-apigateway:
      container_name: search-apigateway
      build: ./search-apigateway
      ports:
        - "8095:8095"
      depends_on:
        server-config:
          condition: service_healthy
      links:
        - server-config
        - eureka-server
        - search-service


