DROP TABLE IF EXISTS SEARCH_TRIP;
DROP TABLE IF EXISTS SEARCH_INVENTORY;
DROP TABLE IF EXISTS SEARCH_PRICE;

CREATE TABLE IF NOT EXISTS SEARCH_INVENTORY (
  inv_id bigint(20) NOT NULL AUTO_INCREMENT,
  count int(11) DEFAULT NULL,
  PRIMARY KEY (inv_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SEARCH_PRICE (
  price_id bigint(20) NOT NULL AUTO_INCREMENT,
  currency varchar(255) DEFAULT NULL,
  price_amount varchar(255) DEFAULT NULL,
  PRIMARY KEY (price_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SEARCH_TRIP (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  bus_number varchar(255) DEFAULT NULL,
  destination varchar(255) DEFAULT NULL,
  origin varchar(255) DEFAULT NULL,
  trip_date varchar(255) DEFAULT NULL,
  inv_id bigint(20) DEFAULT NULL,
  price_id bigint(20) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (inv_id) REFERENCES SEARCH_INVENTORY (inv_id),
  CONSTRAINT FOREIGN KEY (price_id) REFERENCES SEARCH_PRICE (price_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;